# Site settings
title: Door Number Three
header-img: img/home-bg.png
email: junyoungkwon@hotmail.com
copyright_name: junyoungkwon
description: > # this means to ignore newlines until "baseurl:"
  I wanna see what's behind.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  junyoungkwon
learn_profile: junyoungkwon
email_username: junyoungkwon@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
